name: class_rep
description: "Class-Rep — a lightweight, shareable timetable app with comments, optional media on events, paid “Plus” subscriptions (₦800/mo), and creator rewards for popular timetable creators."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Updated for broader compatibility

dependencies:
  flutter:
    sdk: flutter

  # Supabase Client
  supabase_flutter: ^2.5.0

  # UI & Utilities
  intl: ^0.19.0
  table_calendar: ^3.1.2
  permission_handler: ^11.3.1
  share_plus: ^9.0.0
  http: ^1.2.1
  audioplayers: ^6.0.0
  flutter_dotenv: ^5.1.0
  uuid: ^4.4.0
  image_picker: ^1.1.2
  dotted_border: ^2.1.0 # Corrected version for consistency
  timeago: ^3.6.0

  # Icons
  cupertino_icons: ^1.0.2
  url_launcher: ^6.3.2
  firebase_core: ^3.4.0
  firebase_messaging: ^15.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # Updated to a more recent version
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon" # Or true for default name
  ios: true
  image_path: "assets/images/app_icon.png" # Path to your 1024x1024 PNG icon
  min_sdk_android: 21 # Set to your app's minimum Android SDK version
  remove_alpha_ios: true # Recommended for iOS
  adaptive_icon_background: "#1A1B2C" # Your darkSuedeNavy color
  adaptive_icon_foreground: "assets/images/app_icon_foreground.png" # See Step 4 for this

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - .env

  # This new section adds the custom font to your app
  fonts:
    - family: LeagueSpartan
      fonts:
        - asset: assets/fonts/LeagueSpartan-Bold.ttf
          weight: 700 # This number corresponds to FontWeight.bold