name: class_rep
description: "Class-Rep — a lightweight, shareable timetable app with comments, optional media on events, paid “Plus” subscriptions (₦800/mo), and creator rewards for popular timetable creators."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Supabase Client
  supabase_flutter: ^2.5.0

  # UI & Utilities
  intl: ^0.19.0
  table_calendar: ^3.1.2
  permission_handler: ^11.3.1
  share_plus: ^9.0.0
  http: ^1.2.1
  audioplayers: ^6.0.0
  flutter_dotenv: ^5.1.0
  uuid: ^4.4.0
  image_picker: ^1.1.2 # This is the single, correct entry

  # Icons
  cupertino_icons: ^1.0.2
  dotted_border: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
