name: class_rep
description: "Class-Rep — a lightweight, shareable timetable app with comments, optional media on events, paid “Plus” subscriptions (₦800/mo), and creator rewards for popular timetable creators."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Updated for broader compatibility

dependencies:
  flutter:
    sdk: flutter

  # Supabase Client
  supabase_flutter: ^2.5.0

  # UI & Utilities
  intl: ^0.19.0
  table_calendar: ^3.1.2
  permission_handler: ^11.3.1
  share_plus: ^9.0.0
  http: ^1.2.1
  audioplayers: ^6.0.0
  flutter_dotenv: ^5.1.0
  uuid: ^4.4.0
  image_picker: ^1.1.2
  dotted_border: ^2.1.0 # Corrected version for consistency

  # Icons
  cupertino_icons: ^1.0.2
  url_launcher: ^6.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # Updated to a more recent version

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - .env

  # This new section adds the custom font to your app
  fonts:
    - family: LeagueSpartan
      fonts:
        - asset: assets/fonts/LeagueSpartan-Bold.ttf
          weight: 700 # This number corresponds to FontWeight.bold