// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK5NZKVbdounhSRwXDj1E_-qKyeiJp2rA',
    appId: '1:918925012241:web:43ea797a8ecc97c6c470b0',
    messagingSenderId: '918925012241',
    projectId: 'class-rep007',
    authDomain: 'class-rep007.firebaseapp.com',
    storageBucket: 'class-rep007.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARk61fMqIkas9rLYJEpMTb9u8ItL9bTjQ',
    appId: '1:918925012241:android:6f5fde48f8b13462c470b0',
    messagingSenderId: '918925012241',
    projectId: 'class-rep007',
    storageBucket: 'class-rep007.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbMzCrjBWOXDFwgP8d0wbhLVGI-9d2wWE',
    appId: '1:918925012241:ios:9658587be6f30fe4c470b0',
    messagingSenderId: '918925012241',
    projectId: 'class-rep007',
    storageBucket: 'class-rep007.firebasestorage.app',
    iosBundleId: 'com.example.classRep',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbMzCrjBWOXDFwgP8d0wbhLVGI-9d2wWE',
    appId: '1:918925012241:ios:9658587be6f30fe4c470b0',
    messagingSenderId: '918925012241',
    projectId: 'class-rep007',
    storageBucket: 'class-rep007.firebasestorage.app',
    iosBundleId: 'com.example.classRep',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCK5NZKVbdounhSRwXDj1E_-qKyeiJp2rA',
    appId: '1:918925012241:web:5bf0b246da6604bcc470b0',
    messagingSenderId: '918925012241',
    projectId: 'class-rep007',
    authDomain: 'class-rep007.firebaseapp.com',
    storageBucket: 'class-rep007.firebasestorage.app',
  );
}
